sudo: required
language: node_js

node_js:
   - node

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm install -g greenkeeper-lockfile@1

before_script:
   - "sh -e /etc/init.d/xvfb start"
   - npm install -g --silent @angular/cli
   - greenkeeper-lockfile-update

script:
   - ng test --single-run --code-coverage

after_script:
   - greenkeeper-lockfile-upload

after_success:
   - npm run codacy

before_deploy:
   - ng build --prod
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    branch: master
    condition: $MY_ENV = super_awesome
